security:
    encoders:
        App\Entity\UserOrigin:
            algorithm: md5
            encode_as_base64: false
            iterations:       1
    providers:
        in_memory: { memory: null }
        in_database:
            entity:
                class: App\Entity\UserOrigin
                property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            provider: in_database

            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: /pointage
                
            
            logout:
                path: security_logout
                target: /user/origin/list

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/pointage, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user/origin/registration, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/permission/liste, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user/origin/list, roles: ROLE_USER }
        - { path: ^/permission/droit/, roles: IS_AUTHENTICATED_FULLY }
        
        
        
