CREATE TABLE `llx_pointages` ( 
 `rowid` BIGINT NOT NULL AUTO_INCREMENT ,
 `fk_employer` INT NOT NULL ,
 `pointage_arrivee` DATETIME NULL ,
 `note_arrivee` VARCHAR(255) NULL ,
 `pointage_depart` DATETIME NULL ,
 `note_depart` VARCHAR(255) NULL ,
 `actif` TINYINT(1) NOT NULL ,
 `fk_user_author` INT NULL ,
 `cree_le` DATETIME NOT NULL ,
 `fk_user_modif` INT NULL ,
 `modifie_le` DATETIME NULL ,
 `description` TEXT NULL ,
 `etat` set('Entrée','Sortie') NOT NULL,
 `total_minute` SMALLINT NULL ,
PRIMARY KEY (`rowid`)) ENGINE = InnoDB;

CREATE TABLE `llx_pointagesFeuilleTemps` ( 
 `rowid` BIGINT NOT NULL AUTO_INCREMENT ,
 `fk_employer` INT NOT NULL ,
 `pointage_arrivee` DATETIME NULL ,
 `note_arrivee` VARCHAR(255) NULL ,
 `pointage_depart` DATETIME NULL ,
 `note_depart` VARCHAR(255) NULL ,
 `actif` TINYINT(1) NULL ,
 `fk_user_author` INT NULL ,
 `cree_le` DATETIME NULL ,
 `fk_user_modif` INT NULL ,
 `modifie_le` DATETIME NULL ,
 `description` TEXT NULL ,
 `etat` set('Entrée','Sortie') NULL,
 `total_minute` SMALLINT NULL ,
 `date` DATE NULL ,
PRIMARY KEY (`rowid`)) ENGINE = InnoDB;